FROM node:20-alpine AS app-builder

WORKDIR /app

COPY package.json package-lock.json .

RUN npm i

FROM node:20-alpine 

WORKDIR /app

COPY --from=app-builder /app/node_modules ./node_modules
COPY --from=app-builder /app/package-lock.json /app/package.json .

COPY . .

CMD ["npm","run","start"]
